"""
Part 4 pipeline.

Consumes the output generated by Part 3.

`run_part4` now accepts Part 3's actual output object
(`ProductEnrichmentPart3`) directly -- it no longer requires the caller to
pre-build a flat dict by hand. A plain dict is still accepted unchanged for
backward compatibility (see `input_adapter.adapt_part3_output`).
"""

from __future__ import annotations

from typing import Any, Callable, Optional

from .input_adapter import adapt_part3_output
from .enrichment import enrich_missing_attributes
from .validation import validate_product
from .evaluation import evaluate_product
from .packaging import package_product


def run_part4(
    part3_output: Any,
    *,
    required_attributes: Optional[list[str]] = None,
    retrieved_sources: Optional[list[dict[str, Any]]] = None,
    llm_call: Optional[Callable] = None,
    lov_values: Optional[dict[str, list[str]]] = None,
    char_limits: Optional[dict[str, int]] = None,
    casing_rules: Optional[dict[str, str]] = None,
) -> dict[str, Any]:

    if required_attributes is None:
        required_attributes = ["manufacturer", "brand"]

    # ---------------------------------------------------------
    # STEP 1
    # Part 3 -> Part 4
    # ---------------------------------------------------------

    product = adapt_part3_output(part3_output)

    # ---------------------------------------------------------
    # STEP 2
    # Enrich missing attributes
    # ---------------------------------------------------------

    enriched = enrich_missing_attributes(
        product,
        required_attributes,
        retrieved_sources=retrieved_sources,
        llm_call=llm_call,
    )

    # ---------------------------------------------------------
    # STEP 3
    # Programmatic validation
    # ---------------------------------------------------------

    violations = validate_product(
        enriched,
        lov_values=lov_values,
        char_limits=char_limits,
        casing_rules=casing_rules,
    )

    # ---------------------------------------------------------
    # STEP 4
    # Evaluation
    # ---------------------------------------------------------

    evaluation = evaluate_product(
        enriched,
        violations,
    )

    # ---------------------------------------------------------
    # STEP 5
    # Package final output
    # ---------------------------------------------------------

    return package_product(
        enriched,
        violations,
        evaluation,
    )


# ============================================================
# RUN PART 4 FOR MULTIPLE PART 3 RESULTS
# ============================================================

def run_part4_batch(
    part3_results: Optional[list[Any]],
    *,
    required_attributes: Optional[list[str]] = None,
    retrieved_sources: Optional[list[dict[str, Any]]] = None,
    llm_call: Optional[Callable] = None,
    lov_values: Optional[dict[str, list[str]]] = None,
    char_limits: Optional[dict[str, int]] = None,
    casing_rules: Optional[dict[str, str]] = None,
) -> list[dict[str, Any]]:

    if part3_results is None:
        return []

    if required_attributes is None:
        required_attributes = ["manufacturer", "brand"]

    return [
        run_part4(
            part3_output=result,
            required_attributes=required_attributes,
            retrieved_sources=retrieved_sources,
            llm_call=llm_call,
            lov_values=lov_values,
            char_limits=char_limits,
            casing_rules=casing_rules,
        )
        for result in part3_results
    ]


# ============================================================
# PART 3 -> PART 4
# ============================================================

def run_part4_from_part3(
    part3_results: Optional[list[Any]],
    *,
    required_attributes: Optional[list[str]] = None,
    retrieved_sources: Optional[list[dict[str, Any]]] = None,
    llm_call: Optional[Callable] = None,
    lov_values: Optional[dict[str, list[str]]] = None,
    char_limits: Optional[dict[str, int]] = None,
    casing_rules: Optional[dict[str, str]] = None,
) -> list[dict[str, Any]]:

    if required_attributes is None:
        required_attributes = ["manufacturer", "brand"]

    return run_part4_batch(
        part3_results=part3_results,
        required_attributes=required_attributes,
        retrieved_sources=retrieved_sources,
        llm_call=llm_call,
        lov_values=lov_values,
        char_limits=char_limits,
        casing_rules=casing_rules,
    )
